apiVersion: v1
kind: Service
metadata:
  name: adguard-home-ingress
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home-ingress
    app.kubernetes.io/part-of: adguard-home
spec:
  type: LoadBalancer
  ports:
    - name: http-ingress
      port: 8080
      targetPort: 80
      protocol: TCP
    - name: http-setup-ingress
      port: 3000
      targetPort: 3000
      protocol: TCP
    - name: dns-tcp-ingress
      port: 53
      targetPort: 53
      protocol: TCP
    - name: dns-udp-ingress
      port: 53
      targetPort: 53
      protocol: UDP
    - name: tcp-tls-ingress
      port: 853
      targetPort: 853
      protocol: TCP
    - name: udp-quic-ingress
      port: 784
      targetPort: 784
      protocol: UDP
  selector:
    app.kubernetes.io/name: adguard-home-ingress
    app.kubernetes.io/part-of: adguard-home
