controller:
  containerPort:
    http: 80
    https: 443
  service:
    ports:
      # -- Port the external HTTP listener is published with.
      http: 8080
      # -- Port the external HTTPS listener is published with.
      https: 10443
    targetPorts:
      # -- Port of the ingress controller the external HTTP listener is mapped to.
      http: http
      # -- Port of the ingress controller the external HTTPS listener is mapped to.
      https: https
