---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  53: "adguard-home/adguard-home-service:53"
  853: "adguard-home/adguard-home-service:853"
  5443: "adguard-home/adguard-home-service:5443"
  6060: "adguard-home/adguard-home-service:6060"
  10443: "adguard-home/adguard-home-service:443"
  13000: "adguard-home/adguard-home-service::3000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  53: "adguard-home/adguard-home-service:53"
  67: "adguard-home/adguard-home-service:67"
  68: "adguard-home/adguard-home-service:68"
  853: "adguard-home/adguard-home-service:853"
  5443: "adguard-home/adguard-home-service:5443"
  10443: "adguard-home/adguard-home-service:443"
  13000: "adguard-home/adguard-home-service:3000"
