---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-tcp
  namespace: ingress-nginx
data:
  10080-tcp: "adguard-home/adguard-home:10080"
  13000-tcp: "adguard-home/adguard-home:13000"
  53-tcp: "adguard-home/adguard-home:53"
  853-tcp: "adguard-home/adguard-home:853"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-nginx-udp
  namespace: ingress-nginx
data:
  53-udp: "adguard-home/adguard-home:53"
  784-udp: "adguard-home/adguard-home:784"
