---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tcp-services
  namespace: ingress-nginx
data:
  13000: "adguard-home/adguard-home::13000"
  53: "adguard-home/adguard-home:53"
  853: "dguard-home/adguard-home:853"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: udp-services
  namespace: ingress-nginx
data:
  53: "adguard-home/adguard-home:53"
  67: "adguard-home/adguard-home:67"
  853: "adguard-home/adguard-home:853"
  784: "adguard-home/adguard-home:784"
