apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  selector:
    app.kubernetes.io/name: adguard-home
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 3000
      name: http-setup
    - protocol: TCP
      port: 30080
      targetPort: 30080
      name: http
    - protocol: UDP
      port: 53
      targetPort: 53
      name: dns-udp
    - protocol: TCP
      port: 53
      targetPort: 53
      name: dns-tcp
    - protocol: TCP
      port: 853
      targetPort: 853
      name: dns-tls
    - protocol: UDP
      port: 784
      targetPort: 784
      name: dns-quic
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-web
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  selector:
    app.kubernetes.io/name: adguard-home
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-setup
  namespace: adguard-home
  labels:
    app.kubernetes.io/name: adguard-home
spec:
  selector:
    app.kubernetes.io/name: adguard-home
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - protocol: TCP
      port: 13000
      targetPort: 3000
      name: http-setup
