name: Generate GitHub Pages

on:
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  pages: write
  id-token: write

jobs:
  build-index:
    name: Build Index
    runs-on: ubuntu-latest
    env:
      AUTHOR_USER: helm-chart-bot
      AUTHOR_EMAIL: helm-chart-bot[bot]@users.noreply.github.com
    steps:
      - name: Generate Token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.BOT_APP_ID }}
          private-key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Add Helm repos
        run: |
          ./scripts/add-helm-repos.sh

      - name: Remove readme images
        run: |
          set -x
          for f in charts/**/README.md; do
            sed -i '/^<img .* alt=".* logo"/,+1d' "$f"
          done

      - name: Install Helm
        uses: azure/setup-helm@v4
        env:
          GITHUB_TOKEN: "${{ steps.app-token.outputs.token }}"

      - name: Package charts
        id: package_charts
        run: |
          changed_charts=""
          for dir in charts/*; do
            chart_name="$(basename "$dir")"
            version="$(yq '.version' "$dir/Chart.yaml")"
            if ! git rev-parse "$chart_name-${version#v}" &>/dev/null; then
              echo "Packaging chart $chart_name..."
              cr package --package-path=.cr-release-packages "$dir"
              changed_charts+="$chart_name,"
            fi
          done
          echo "changed_charts=${changed_charts%,}" >> $GITHUB_OUTPUT

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.6.0
        with:
          config: ./docs/cr.yaml
          skip_packaging: true
          skip_existing: true
          skip_upload: true
          mark_as_latest: true
          packages_with_index: false
        env:
          CR_TOKEN: "${{ steps.app-token.outputs.token }}"

  build-docs:
    name: Build Docs
    runs-on: ubuntu-latest
    needs: [build-index]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
          cache-dependency-path: docs/requirements.txt

      - name: MkDocs cache
        uses: actions/cache@v4
        with:
          path: docs/.cache
          key: ${{ runner.os }}-mkdocs-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-mkdocs-

      - name: Install dependencies
        run: pip install -r docs/requirements.txt

      - name: Build docs
        working-directory: docs
        env:
          REPO_NAME: ${{ github.repository }}
          REPO_URL: ${{ github.server_url }}/${{ github.repository }}
        run: mkdocs build

      - name: Compress
        run: tar -czvf docs.tar.gz -C docs site

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docs
          path: docs.tar.gz

  deploy-site:
    name: Deploy Site
    runs-on: ubuntu-latest
    needs: [ build-index ]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Helm index
        uses: actions/checkout@v4
        with:
          path: helm-index
          ref: refs/heads/helm-index

      - name: Download docs artifact
        uses: actions/download-artifact@v4
        with:
          name: docs

      - name: Decompress docs
        run: tar -xzvf docs.tar.gz

      - name: Move Helm index to docs
        run: mv helm-index/* site

      - name: Upload release artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
